networks:
  recognaizer:
   driver: bridge
   name: recognaizer
   external: true

services:
  nginx:
    restart: always
    container_name: nginx-proxy
    build:
      context: .
    environment :
      - DOMEN_NAME=ysynytsia.space
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/www/letsencrypt/:/data/letsencrypt/:ro
      - /etc/letsencrypt/:/etc/letsencrypt/:ro
    depends_on:
      - ui
      - api
    networks:
      - recognaizer
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - api
    networks:
      - recognaizer
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file: "./server/.env"
    restart: always
    networks:
      - recognaizer
