version: "3.8"

networks:
  expert:
   driver: bridge
   name: expert
   external: true

services:
  nginx:
    restart: always
    container_name: nginx-proxy
    image: ${DC_IMAGE_NAME_SERVER}:${DC_IMAGE_TAG}
    environment :
      - DOMEN_NAME=${DOMEN_NAME}
    ports:
      - "80:80"
      - "443:443"
      - "8020:8020"
      - "5118:5118"
    volumes:
      - /var/www/letsencrypt/:/data/letsencrypt/:ro
      - /etc/letsencrypt/:/etc/letsencrypt/:ro
    depends_on:
      - ui
      - api
      - instruction_expert
    networks:
      - expert
  ui:
    image: ${DC_IMAGE_NAME_UI}:${DC_IMAGE_TAG}
    restart: always
    depends_on:
      - api
    networks:
      - expert
  api:
    image: ${DC_IMAGE_NAME_API}:${DC_IMAGE_TAG}
    command: npm run start:${SM_STAGE}
    restart: always
    env_file: "./api/.env"
    networks:
      - expert
  instruction_expert:
    image: ${DC_IMAGE_NAME_EXPERT}:${DC_IMAGE_TAG}
    env_file: "./expert/.env"
    restart: always
    depends_on:
      - api
    networks:
      - expert
