version: "3.8"

networks:
  recognaizer:
   driver: bridge
   name: recognaizer
   external: true

services:
  nginx:
    restart: always
    container_name: nginx-proxy
    image: nginx:stable-alpine
    ports:
      - 3011:80
    volumes:
      - './nginx_def_dev.conf:/etc/nginx/nginx.conf'
    depends_on:
      - ui
      - server
    networks:
      - recognaizer
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - server
    networks:
      - recognaizer
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file: "./server/.env"
    restart: always
    networks:
      - recognaizer
